a = input ('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços? ', a.isspace())
print('é um numero?', a.isnumeric())
print('é alfabetico', a.isalpha())
print('é alfanumerico', a.isalnum())
print('esta em minúsculas?', a.islower())
print('esta em maiúsculas', a.isupper())
print('esta capitalizada?', a.istitle())
